### PR TITLE
Bug/user controller namechange

### LINKED ISSUE #31: Fix MessageController instead of user controller

### PR DESCRIPTION
**Pull request by MuresanIA**

### CODE REVIEW

**Comment by MuresanIA** [comment]
Fixed

File: src/main/java/com/mia/BuhaiCommunications/model/User.java [hunk 1]
```diff
@@ -0,0 +1,2 @@
+package com.mia.BuhaiCommunications.model;public class User {
+}
```
Comment (soosheehd) [inline src/main/java/com/mia/BuhaiCommunications/model/User.java:2]: you're missing an empty line here
